SELECT `Top Charites`.`type`,
    `Top Charites`.`order_no`,
    `Top Charites`.`reg_charity_number`,
    `Top Charites`.`charity_name`,
    `Top Charites`.`Income - Donations and legacies`,
    `Top Charites`.`Income - Other trading activities`,
    `Top Charites`.`Income - Investments`,
    `Top Charites`.`Income - Charitable activities`,
    `Top Charites`.`Income - Other`,
    `Top Charites`.`Income - Total`,
    `Top Charites`.`Investment gains (losses)`,
    `Top Charites`.`Income - growth`,
    `Top Charites`.`Expenditure - Raising funds`,
    `Top Charites`.`Expenditure - Charitable`,
    `Top Charites`.`Expenditure - Other`,
    `Top Charites`.`Expenditure - Total`,
    `Top Charites`.`Expenditure - Growth`,
    `Top Charites`.`Own use assets`,
    `Top Charites`.`Long-term investments`,
    `Top Charites`.`Define benefit pension scheme or liability`,
    `Top Charites`.`Other assets`,
    `Top Charites`.`Total liabilities`,
    `Top Charites`.`Trustees`,
    `Top Charites`.`Employees`,
    `Top Charites`.`Volunteers`
FROM `charity_data`.`Top Charites`;
